---
title: "Spam Classification with SVMs"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initialization

```{r}
rm(list=ls())
sources <- c("emailFeatures.R","getVocabList.R","linearKernel.R","bsxfun.R",
             "processEmail.R","svmPredict.R","svmTrain.R","meshgrid.R")

for (i in 1:length(sources)) {
  cat(paste("Loading ",sources[i],"\n"))
  source(sources[i])
}
```

## Part 1: Email Preprocessing
```{r}
cat(sprintf('\nPreprocessing sample email (emailSample1.txt)\n'))

# Extract Features
fName <- 'emailSample1.txt'
file_contents <- readChar(fName,file.info(fName)$size)
word_indices  <- processEmail(file_contents)

# Print Stats
cat(sprintf('Word Indices: \n'))
cat(sprintf(' %d', word_indices))
cat(sprintf('\n\n'))
```

## Part 2: Feature Extraction

```{r}
cat(sprintf('\nExtracting features from sample email (emailSample1.txt)\n'))

# Extract Features
fName <- 'emailSample1.txt'
file_contents <- readChar(fName,file.info(fName)$size)
word_indices  <- processEmail(file_contents)
features      <- emailFeatures(word_indices)

# Print Stats
cat(sprintf('Length of feature vector: %d\n', length(features)))
cat(sprintf('Number of non-zero entries: %d\n', sum(features > 0)))
```

## Part 3: Train Linear SVM for Spam Classification

```{r}
# Load the Spam Email dataset
# You will have X, y in your environment
load('spamTrain.Rda')
list2env(data,.GlobalEnv)
rm(data)

cat(sprintf('\nTraining Linear SVM (Spam Classification)\n'))
cat(sprintf('(this may take 1 to 2 minutes) ...\n'))

C <- 0.1
model <- svmTrain(X, y, C, linearKernel)

p <- svmPredict(model, X)

cat(sprintf('Training Accuracy: %f\n', mean(p==y) * 100))
```

## Part 4: Test Spam Classification

```{r}
# Load the test dataset
# You will have Xtest, ytest in your environment
load('spamTest.Rda')
list2env(data,.GlobalEnv)
rm(data)

cat(sprintf('\nEvaluating the trained Linear SVM on a test set ...\n'))

p <- svmPredict(model, Xtest)

cat(sprintf('Test Accuracy: %f\n', mean(p==ytest) * 100))
```

## Part 5: Top Predictors of Spam

```{r}
# Sort the weights and obtin the vocabulary list
srt <- sort(model$w, decreasing = TRUE,index.return=TRUE)
weight <- srt$x
idx <- srt$ix
rm(srt)

vocabList <- getVocabList()

cat(sprintf('\nTop predictors of spam: \n'))
for (i in 1:15)
    cat(sprintf(' %-15s (%f) \n', vocabList[idx[i]], weight[i]))

cat(sprintf('\n\n'))
```

## Part 6: Try Your Own Emails

```{r}
# Set the file to be read in (change this to spamSample2.txt,
# emailSample1.txt or emailSample2.txt to see different predictions on
# different emails types). Try your own emails as well!
fName <- 'spamSample1.txt'

# Read and predict
file_contents <- readChar(fName,file.info(fName)$size)
word_indices  <- processEmail(file_contents)
x             <- emailFeatures(word_indices)
p <- svmPredict(model, x)

cat(sprintf('\nProcessed %s\n\nSpam Classification: %d\n', fName, p))
```